"""Pin an Orca --export-settings (no input/project) snapshot and preset ownership.

Usage: capture_defaults.py EXPORT_JSON ORCA_SOURCE OUTPUT_INC
The export must come from an isolated datadir, without --load-settings or a 3MF.
Values come from the executable; C++ option lists supply ownership, not values.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess


def option_list(text, name):
    # These initializers contain option names only. Remove comments before
    # extracting strings so disabled historical options do not acquire ownership.
    text = re.sub(r'/\*.*?\*/|//[^\n]*', '', text, flags=re.S)
    match = re.search(r'\b' + re.escape(name) + r'\s*(?:=\s*)?\{(.*?)\};', text, re.S)
    if not match:
        raise ValueError(f'Missing option list: {name}')
    return set(re.findall(r'"([a-zA-Z0-9_]+)"', match[1]))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('export', type=Path)
    parser.add_argument('source', type=Path)
    parser.add_argument('output', type=Path)
    args = parser.parse_args()
    defaults = json.loads(args.export.read_text(encoding='utf-8-sig'))
    preset = args.source / 'src/libslic3r/Preset.cpp'
    config = args.source / 'src/libslic3r/PrintConfig.cpp'
    preset_text, config_text = preset.read_text(encoding='utf-8'), config.read_text(encoding='utf-8')
    groups = {
        'process': option_list(preset_text, 's_Preset_print_options'),
        'filament': option_list(preset_text, 's_Preset_filament_options'),
        'machine': option_list(preset_text, 's_Preset_printer_options')
            | option_list(preset_text, 's_Preset_machine_limits_options')
            | option_list(config_text, 'm_extruder_option_keys'),
    }
    result = {'evidence': {
        'version': defaults['version'],
        'capture': 'Orca CLI --export-settings with no input, no loaded profiles and an isolated datadir',
        'export_sha256': hashlib.sha256(args.export.read_bytes()).hexdigest(),
        'ownership_source_commit': subprocess.check_output(['git', '-c', 'safe.directory=' + args.source.resolve().as_posix(), '-C', str(args.source), 'rev-parse', 'HEAD'], text=True).strip(),
        'ownership_files': {str(p.relative_to(args.source)): hashlib.sha256(p.read_bytes()).hexdigest() for p in (preset, config)},
    }, 'defaults': {kind: {k: defaults[k] for k in sorted(keys) if k in defaults} for kind, keys in groups.items()},
        'not_exported': {kind: sorted(keys - defaults.keys()) for kind, keys in groups.items()},
        'unowned_export_fields': sorted(defaults.keys() - set.union(*groups.values()))}
    serialized = json.dumps(result, indent=2)
    # Separate tokens stay below MSVC's individual string-literal length limit.
    args.output.write_text('// Generated by tests/orca_profile_import/capture_defaults.py. Do not edit values by hand.\n'
                           + ',\n'.join('R"orca_defaults(' + serialized[i:i+8000] + ')orca_defaults"'
                                       for i in range(0, len(serialized), 8000)) + '\n', encoding='utf-8')
    print('Captured defaults:', {kind: len(values) for kind, values in result['defaults'].items()})


if __name__ == '__main__':
    main()
