#pragma once


#include "Slic3r/Domain/Constants.hpp"
#include "Slic3r/Domain/Point.hpp"

namespace Slic3r::Domain::SLA {

// An enum to keep track of where the current points on the ModelObject came from.
enum class PointsStatus {
    NoPoints,           // No points were generated so far.
    Generating,     // The autogeneration algorithm triggered, but not yet finished.
    AutoGenerated,  // Points were autogenerated (i.e. copied from the backend).
    UserModified    // User has done some edits.
};

// Reason of automatic support placement usage
enum class SupportPointType {
    manual_add,
    island, // no move, island should be grouped
    slope,
    //thin,
    //stability,
    //edge
};

/// <summary>
/// Stereolithography(SLA) support point
/// </summary>
struct SupportPoint
{
    // Position on model surface
    Vec3f pos = Vec3f::Zero(); // [in mm]

    // radius of the touching interface
    // Also define force it must keep
    float head_front_radius = 0.f; // [in mm]

    // type
    SupportPointType type{SupportPointType::manual_add};

    bool is_island() const { return type == SupportPointType::island; }

    // unsaved changes + cache invalidation
    bool operator==(const SupportPoint &sp) const;

    bool operator!=(const SupportPoint &sp) const;

};
using SupportPoints = std::vector<SupportPoint>;

} // namespace Slic3r::Domain::SLA
