#pragma once

#include <string_view>
#include <optional>
#include <map>
#include "Slic3r/Domain/CustomGCode.hpp"
#include "Slic3r/Domain/GCodeExtrusionRole.hpp"
#include "Slic3r/Domain/Types.hpp"

using namespace std::literals;

namespace Slic3r::Biz::libpgcode {

static constexpr uint8_t MIN_EXTRUDERS_COUNT = 1;

static constexpr float DEFAULT_TOOLPATH_WIDTH  = 0.4f;
static constexpr float DEFAULT_TOOLPATH_HEIGHT = 0.2f;
static constexpr float DEFAULT_WIPE_WIDTH  = 0.05f;
static constexpr float DEFAULT_WIPE_HEIGHT = 0.05f;

static constexpr float DEFAULT_FILAMENT_DIAMETER = 1.75f;
static constexpr float DEFAULT_FILAMENT_DENSITY  = 1.245f;
static constexpr float DEFAULT_FILAMENT_COST     = 0.0f;

static const Domain::Vec3f DEFAULT_EXTRUDER_OFFSET = Domain::Vec3f::Zero();

static constexpr float DEFAULT_ACCELERATION         = 1500.0f; // Prusa Firmware 1_75mm_MK2
static constexpr float DEFAULT_RETRACT_ACCELERATION = 1500.0f; // Prusa Firmware 1_75mm_MK2
static constexpr float DEFAULT_TRAVEL_ACCELERATION  = 1250.0f;

static const std::string DEFAULT_EXTRUDER_STR_COLOR = "#FF8000";
// gray color for pause print or custom G-code
static const std::string DUMMY_STR_COLOR = "#808080";

static const std::vector<std::string> DEFAULT_COLOR_CHANGE_COLORS = {
    "#0B2C7A", //  11,  44, 122
    "#1C8891", //  28, 136, 145
    "#AAF200", // 170, 242,   0
    "#F5CE0A", // 245, 206,  10
    "#D16830", // 209, 104,  48
    "#942616", // 148,  38,  22
};

static constexpr size_t GCODE_EXTRUSION_ROLES_COUNT = size_t(Domain::GCodeExtrusionRole::Count);
using GCodeExtrusionRoles = std::vector<Domain::GCodeExtrusionRole>;

enum class MoveType : uint8_t
{
    Noop,
    Retract,
    Unretract,
    Seam,
    ToolChange,
    ColorChange,
    PausePrint,
    CustomGCode,
    Travel,
    Wipe,
    Extrude,
    Flush,
    COUNT
};

static constexpr size_t MOVE_TYPES_COUNT = size_t(MoveType::COUNT);

using MoveTypes = std::vector<MoveType>;

enum class GCodeProducer : uint8_t
{
    AnkerMakeStudio,
    BambuStudio,
    CraftWare,
    Cura,
    KISSlicer,
    ideaMaker,
    OrcaSlicer,
    PrusaSlicer,
    Simplify3D,
    Slic3r,
    Slic3rPE,
    SuperSlicer,
    XDesktop,
    Unknown,
    COUNT
};

static constexpr size_t GCODE_PRODUCERS_COUNT = size_t(GCodeProducer::COUNT);

static const std::vector<std::pair<GCodeProducer, std::string_view>> PRODUCERS = {
    { GCodeProducer::AnkerMakeStudio, "generated by AnkerMake Studio"sv },
    { GCodeProducer::BambuStudio,     "BambuStudio"sv },
    { GCodeProducer::CraftWare,       "CraftWare"sv },
    { GCodeProducer::Cura,            "Cura_SteamEngine"sv },
    { GCodeProducer::KISSlicer,       "KISSlicer"sv },
    { GCodeProducer::ideaMaker,       "ideaMaker"sv },
    { GCodeProducer::OrcaSlicer,      "generated by OrcaSlicer"sv },
    { GCodeProducer::PrusaSlicer,     "generated by PrusaSlicer"sv },
    { GCodeProducer::Simplify3D,      "generated by Simplify3D(R)"sv },
    { GCodeProducer::Slic3r,          "generated by Slic3r"sv },
    { GCodeProducer::Slic3rPE,        "generated by Slic3r Prusa Edition"sv },
    { GCodeProducer::SuperSlicer,     "generated by SuperSlicer"sv },
    { GCodeProducer::XDesktop,        "generated by XDesktop"sv },
};

enum class TimeMode : uint8_t
{
    Normal,
    Stealth,
    COUNT
};

static constexpr size_t TIME_MODES_COUNT = size_t(TimeMode::COUNT);

using Times = std::array<float, TIME_MODES_COUNT>;
using TimeModes = std::vector<TimeMode>;

struct MoveVertex
{
    MoveType type{ MoveType::Noop };
    Domain::GCodeExtrusionRole extrusion_role{ Domain::GCodeExtrusionRole::None };
    uint8_t extruder_id{ 0 };
    uint8_t cp_color_id{ 0 };
    uint32_t gcode_id{ 0 };
    uint32_t layer_id{ 0 };
    bool internal_only{ false };
    float delta_extruder{ 0.0f }; // mm
    float feedrate{ 0.0f }; // mm/s
    float actual_feedrate{ 0.0f }; // mm/s
    float width{ 0.0f }; // mm
    float height{ 0.0f }; // mm
    float mm3_per_mm{ 0.0f };
    float fan_speed{ 0.0f }; // percentage
    float temperature{ 0.0f }; // Celsius degrees
    float mass{ 0.0f }; // g
    Domain::Vec3f position{ Domain::Vec3f::Zero() }; // mm
    Times time{}; // s

    float volumetric_rate() const;
    float actual_volumetric_rate() const;
    bool is_extrusion() const;
    bool is_travel() const;
    bool is_option() const;
    bool is_wipe() const;
    bool is_custom_gcode() const;
};

static const MoveVertex DUMMY_MOVE_VERTEX = MoveVertex();

using MoveVertices = std::vector<MoveVertex>;

enum class PositioningType : uint8_t
{
    Absolute,
    Relative,
    COUNT
};

static constexpr size_t POSITIONING_TYPES_COUNT = size_t(PositioningType::COUNT);

enum class OptionType : uint8_t
{
    Travels,
    Wipes,
    Retractions,
    Unretractions,
    Seams,
    ToolChanges,
    ColorChanges,
    PausePrints,
    CustomGCodes,
    CenterOfGravity,
    ToolMarker,
    COUNT
};

static constexpr size_t OPTION_TYPES_COUNT = size_t(OptionType::COUNT);

using OptionTypes = std::vector<OptionType>;

enum class UnitsSystem : uint8_t
{
    SI,
    Imperial,
    COUNT
};

static constexpr size_t UNITS_SYSTEMS_COUNT = size_t(UnitsSystem::COUNT);

enum class UnitsType : uint8_t
{
    Bytes,
    KiloBytes,
    MegaBytes,
    GigaBytes,
    TeraBytes,
    Celsius,
    Days,
    Farhenheit,
    Feet,
    FeetCube,
    Grams,
    Hours,
    Inches,
    InchesPerSecond,
    InchesCube,
    InchesCubePerSecond,
    Meters,
    MetersCube,
    Millimeters,
    MillimetersPerSecond,
    MillimetersPerMinute,
    MillimetersCube,
    MillimetersCubePerSecond,
    Minutes,
    Ounces,
    Seconds,
    Years,
    COUNT
};

static constexpr size_t UNITS_TYPES_COUNT = size_t(UnitsType::COUNT);

struct Conversion
{
    UnitsType in;
    UnitsType out;
    std::function<float(float)> conversion_function;
};

static const float INCHES_TO_MILLIMETERS = 25.4f;
static const float MILLIMETERS_TO_INCHES = 1.0f / INCHES_TO_MILLIMETERS;
static const float METERS_TO_FEET = 3.28084f;
static const float FEET_TO_METERS = 1.0f / METERS_TO_FEET;
static const float METERS_TO_MILLIMETERS = 1000.0f;
static const float MILLIMETERS_TO_METERS = 1.0f / METERS_TO_MILLIMETERS;
static const float FEET_TO_INCHES = 12.0f;
static const float INCHES_TO_FEET = 1.0f / FEET_TO_INCHES;
static const float CUBED_INCHES_TO_CUBED_MILLIMETERS = INCHES_TO_MILLIMETERS * INCHES_TO_MILLIMETERS * INCHES_TO_MILLIMETERS;
static const float CUBED_MILLIMETERS_TO_CUBED_INCHES = MILLIMETERS_TO_INCHES * MILLIMETERS_TO_INCHES * MILLIMETERS_TO_INCHES;
static const float CUBED_METERS_TO_CUBED_FEET = METERS_TO_FEET * METERS_TO_FEET * METERS_TO_FEET;
static const float CUBED_FEET_TO_CUBED_METERS = FEET_TO_METERS * FEET_TO_METERS * FEET_TO_METERS;
static const float CUBED_METERS_TO_CUBED_MILLIMETERS = METERS_TO_MILLIMETERS * METERS_TO_MILLIMETERS * METERS_TO_MILLIMETERS;
static const float CUBED_MILLIMETERS_TO_CUBED_METERS = MILLIMETERS_TO_METERS * MILLIMETERS_TO_METERS * MILLIMETERS_TO_METERS;
static const float CUBED_FEET_TO_CUBED_INCHES = FEET_TO_INCHES * FEET_TO_INCHES * FEET_TO_INCHES;
static const float CUBED_INCHES_TO_CUBED_FEET = INCHES_TO_FEET * INCHES_TO_FEET * INCHES_TO_FEET;
static const float GRAMS_TO_OUNCES = 0.035274f;
static const float OUNCES_TO_GRAMS = 1.0f / GRAMS_TO_OUNCES;
static const float MINUTES_TO_SECONDS = 60.0f;
static const float SECONDS_TO_MINUTES = 1.0f / MINUTES_TO_SECONDS;

static const std::vector<Conversion> CONVERSIONS = {
    { UnitsType::Celsius,                  UnitsType::Farhenheit,               [](float value){ return (value * 1.8f) + 32.0f; } },
    { UnitsType::Farhenheit,               UnitsType::Celsius,                  [](float value){ return (value - 32.0f) * 0.55555f; } },
    { UnitsType::Feet,                     UnitsType::Inches,                   [](float value){ return value * FEET_TO_INCHES; } },
    { UnitsType::Feet,                     UnitsType::Meters,                   [](float value){ return value * FEET_TO_METERS; } },
    { UnitsType::Grams,                    UnitsType::Ounces,                   [](float value){ return value * GRAMS_TO_OUNCES; } },
    { UnitsType::Inches,                   UnitsType::Feet,                     [](float value){ return value * INCHES_TO_FEET; } },
    { UnitsType::Inches,                   UnitsType::Millimeters,              [](float value){ return value * INCHES_TO_MILLIMETERS; } },
    { UnitsType::InchesPerSecond,          UnitsType::MillimetersPerSecond,     [](float value){ return value * INCHES_TO_MILLIMETERS; } },
    { UnitsType::InchesCube,               UnitsType::MillimetersCube,          [](float value){ return value * CUBED_INCHES_TO_CUBED_MILLIMETERS; } },
    { UnitsType::InchesCubePerSecond,      UnitsType::MillimetersCubePerSecond, [](float value){ return value * CUBED_INCHES_TO_CUBED_MILLIMETERS; } },
    { UnitsType::Meters,                   UnitsType::Millimeters,              [](float value){ return value * METERS_TO_MILLIMETERS; } },
    { UnitsType::Meters,                   UnitsType::Feet,                     [](float value){ return value * METERS_TO_FEET; } },
    { UnitsType::MetersCube,               UnitsType::MillimetersCube,          [](float value){ return value * CUBED_METERS_TO_CUBED_MILLIMETERS; } },
    { UnitsType::Millimeters,              UnitsType::Inches,                   [](float value){ return value * MILLIMETERS_TO_INCHES; } },
    { UnitsType::MillimetersPerSecond,     UnitsType::InchesPerSecond,          [](float value){ return value * MILLIMETERS_TO_INCHES; } },
    { UnitsType::MillimetersPerSecond,     UnitsType::MillimetersPerMinute,     [](float value){ return value * MINUTES_TO_SECONDS; } },
    { UnitsType::MillimetersPerMinute,     UnitsType::MillimetersPerSecond,     [](float value){ return value * SECONDS_TO_MINUTES; } },
    { UnitsType::MillimetersCube,          UnitsType::InchesCube,               [](float value){ return value * CUBED_MILLIMETERS_TO_CUBED_INCHES; } },
    { UnitsType::MillimetersCubePerSecond, UnitsType::InchesCubePerSecond,      [](float value){ return value * CUBED_MILLIMETERS_TO_CUBED_INCHES; } },
    { UnitsType::Millimeters,              UnitsType::Meters,                   [](float value){ return value * MILLIMETERS_TO_METERS; } },
    { UnitsType::MillimetersCube,          UnitsType::MetersCube,               [](float value){ return value * CUBED_MILLIMETERS_TO_CUBED_METERS; } },
    { UnitsType::Ounces,                   UnitsType::Grams,                    [](float value){ return value * OUNCES_TO_GRAMS; } },
    { UnitsType::Minutes,                  UnitsType::Seconds,                  [](float value){ return value * MINUTES_TO_SECONDS; } },
    { UnitsType::Seconds,                  UnitsType::Minutes,                  [](float value){ return value * SECONDS_TO_MINUTES; } },
};

struct PrintSettings
{
    std::string print;
    std::string printer;
    std::vector<std::string> filament;

    bool has_data() const;
    void reset();
};

enum class Tags : uint8_t
{
    Role,
    Wipe_Start,
    Wipe_End,
    Height,
    Width,
    Layer_Change,
    Color_Change,
    Pause_Print,
    Custom_Code,
    First_Line_M73_Placeholder,
    Last_Line_M73_Placeholder,
    Print_Statistics_Placeholder,
    COUNT
};

static constexpr size_t TAGS_COUNT = size_t(Tags::COUNT);

static const std::vector<std::string_view> RESERVED_TAGS = {
    "TYPE:"sv,
    "WIPE_START"sv,
    "WIPE_END"sv,
    "HEIGHT:"sv,
    "WIDTH:"sv,
    "LAYER_CHANGE"sv,
    "COLOR_CHANGE"sv,
    "PAUSE_PRINT"sv,
    "CUSTOM_GCODE"sv,
    "_GP_FIRST_LINE_M73_PLACEHOLDER"sv,
    "_GP_LAST_LINE_M73_PLACEHOLDER"sv,
    "_GP_PRINT_STATISTICS_PLACEHOLDER"sv
};

enum class CustomTags : uint8_t
{
    Flush_Start,
    Flush_End,
    Exclude_E_Start,
    Exclude_E_End,
    COUNT
};

static const std::vector<std::string_view> CUSTOM_TAGS = {
    "FLUSH_START"sv,
    "FLUSH_END"sv,
    "EXCLUDE_E_START"sv,
    "EXCLUDE_E_END"sv
};

} // namespace Slic3r::Biz::libpgcode
