#pragma once

#include "TimeMachine.hpp"

#include "Slic3r/Biz/libpgcode/ProcessorConfig.hpp"
#include "Slic3r/Domain/Axis.hpp"

namespace Slic3r::Biz::libpgcode {

struct TimeProcessorPlanner
{
    // Size of the firmware planner queue. The old 8-bit Marlins usually just managed 16 trapezoidal blocks.
    // Let's be conservative and plan for newer boards with more memory.
    static constexpr size_t queue_size = 64;
    // The firmware recalculates last planner_queue_size trapezoidal blocks each time a new block is added.
    // We are not simulating the firmware exactly, we calculate a sequence of blocks once a reasonable number of blocks accumulate.
    static constexpr size_t refresh_threshold = queue_size * 4;
};

struct TimeProcessor
{
    // allow to skip the lines M201/M203/M204/M205 generated by GCode::print_machine_envelope() for non-Normal time estimate mode
    bool machine_envelope_processing_enabled{ false };
    // extruder_id is currently used to correctly calculate filament load / unload times into the total print time.
    // This is currently only really used by the MK3 MMU2:
    // extruder_unloaded = true means no filament is loaded yet, all the filaments are parked in the MK3 MMU2 unit.
    bool extruder_unloaded{ true };
    TimeMachines machines;
    // Additional load / unload times for a filament exchange sequence.
    float tool_change_time{};
    MachineLimitsConfig machine_limits;

    void update_machine_accelerations(Domain::GCodeFlavor flavor);

    float minimum_feedrate(TimeMode mode, float feedrate) const;
    float minimum_travel_feedrate(TimeMode mode, float feedrate) const;
    float axis_max_feedrate(TimeMode mode, Domain::Axis axis) const;

    float acceleration(TimeMode mode) const;
    float travel_acceleration(TimeMode mode) const;
    float retract_acceleration(TimeMode mode) const;
    float junction_deviation(TimeMode mode) const;

    float axis_max_acceleration(TimeMode mode, Domain::Axis axis) const;
    float axis_max_jerk(TimeMode mode, Domain::Axis axis) const;

    std::vector<std::pair<Domain::CustomGCode::Type, std::pair<float, float>>>
        custom_gcode_times(TimeMode mode, bool include_remaining) const;

    void reset();
};

} // namespace Slic3r::Biz::libpgcode
