#pragma once

#include "Slic3r/App/Plater/HeightRangeNodeTag.hpp"
#include "Slic3r/App/Render/GeometryManager.hpp"
#include "Slic3r/App/Render/Material.hpp"
#include "Slic3r/App/Render/Texture.hpp"
#include "Slic3r/Domain/BedRef.hpp"
#include "Slic3r/App/Scene/TriangleMeshManager.hpp"
#include "Slic3r/Domain/LayerHeightProfile.hpp"

#include <vector>

namespace Slic3r::App::Render {
class Device;
} // namespace Slic3r::App::Render

namespace Slic3r::App::Scene {
class Node;
class NodeBuilder;
class Scene;
} // namespace Slic3r::App::Scene

namespace Slic3r::Biz::Scene {
struct ObjectSelection;
} // namespace Slic3r::Biz::Scene

namespace Slic3r::Domain {
class ConfigContainer;
class ModelObject;
class Project;
} // namespace Slic3r::Domain

namespace Slic3r::App::Plater {

struct HeightRangeEntry;
using HeightRangeEntries = std::vector<HeightRangeEntry>;

struct LayerHeightParams
{
    /**
     * The regular layer height, applied for all but the first layer, if not overridden by layer ranges
     * or by the variable layer thickness table.
     */
    double layer_height{0.};
    /**
     * Minimum layer height, to be used for the automatic adaptive layer height algorithm,
     * or by an interactive layer height editor.
     */
    double min_layer_height{0.};
    /**
     * Maximum layer height, to be used for the automatic adaptive layer height algorithm,
     * or by an interactive layer height editor.
     */
    double max_layer_height{0.};
    /**
     * Thickness of the first layer. This is either the first print layer thickness if printed without a raft,
     * or a bridging flow thickness if printed over a non-soluble raft,
     * or a normal layer height if printed over a soluble raft.
     */
    double first_object_layer_height{0.};
    /**
     * Is the 1st object layer height fixed, or could it be varied?
     */
    bool first_object_layer_height_fixed{false};
    /**
     * Height of the object to be printed. This value does not contain the raft height.
     * This value is scaled by shrinkage compensation in the Z-axis.
     */
    double object_print_z_height{0.};
    /**
     * Height of the object to be printed. This value does not contain the raft height.
     * This value isn't scaled by shrinkage compensation in the Z-axis.
     */
    double object_print_z_uncompensated_height{0.};
    /**
     * Scaling factor for compensating shrinkage in Z-axis.
     */
    double object_shrinkage_compensation_z{1.0};
    /**
     * Current layer height profile.
     */
    Domain::ZHeightPairs layer_height_profile;
};

LayerHeightParams compute_layer_height_params(
    const Biz::Scene::ObjectSelection& object_selection,
    const Domain::Project& project,
    const Domain::ConfigContainer& config_container,
    const Domain::BedRef& bed_ref
);

/**
 * @brief Checks whether the layer height profile is valid - i.e. it was painted or generated
 * by the variable layer height gizmo. An empty or height-mismatched profile is considered invalid.
 *
 * @param layer_height_profile The layer height profile stored on the model object.
 * @param object_print_z_uncompensated_height The uncompensated print height of the object.
 * @return True if the profile is non-empty and its last Z coordinate matches the object height.
 */
bool is_valid_layer_height_profile(
    const Domain::ZHeightPairs& layer_height_profile,
    double object_print_z_uncompensated_height
);

/**
 * @brief Computes the layer height profile to display. Returns the model profile if it is valid
 * (painted or generated by the variable layer height gizmo), otherwise generates a new profile
 * from the layer config ranges.
 *
 * @param params Layer height parameters containing object dimensions and layer height settings.
 * @param layer_config_ranges Layer config ranges to generate the profile from when no valid
 *        model profile exists.
 * @param layer_height_profile The layer height profile stored on the model object. When empty
 *        (default), the profile is always generated from ranges.
 * @return The valid model profile, or a newly generated profile from ranges.
 */
Domain::ZHeightPairs compute_layer_height_profile(
    const LayerHeightParams& params,
    const Domain::LayerConfigRanges& layer_config_ranges,
    const Domain::ZHeightPairs& layer_height_profile = Domain::ZHeightPairs{}
);

HeightRangeEntries create_height_ranges_from_config(
    const Domain::LayerConfigRanges& layer_config_ranges,
    double default_layer_height
);

/**
 * CPU-side texture data for layer height visualization.
 */
struct LayerHeightTexture
{
    /**
     * Texture data buffer (RGBA).
     */
    std::vector<char> data;
    /**
     * Width of the texture, top level.
     */
    size_t width{0};
    /**
     * Height of the texture, top level.
     */
    size_t height{0};
    /**
     * For how many levels of detail is the data allocated?
     */
    size_t levels{0};
    /**
     * Number of texture cells allocated for the height texture.
     */
    size_t cells{0};

    /**
     * Allocate the texture data buffer based on width, height, and levels.
     */
    void allocate()
    {
        size_t size = width * height * 4; // LOD 0: RGBA
        if (levels >= 2) {
            size += (width / 2) * (height / 2) * 4; // LOD 1: half resolution
        }

        ASSERT(levels <= 2);
        data.assign(size, 0);
    }
};

/**
 * Generate layer height texture from layer height profile.
 *
 * Produces a 2D RGBA texture visualizing layer heights using a color gradient.
 * Supports up to 2 LOD levels for mipmap-based rendering.
 *
 * @param color_layers Layers for palette color mapping.
 * @param stripe_layers Layers for visualizing layer height boundaries via intensity modulation.
 * @param min_layer_height Minimum allowed layer height.
 * @param max_layer_height Maximum allowed layer height.
 * @param layer_height Default layer height.
 * @param object_height Total Z height of the object.
 * @return LayerHeightTexture with allocated and filled texture data.
 */
LayerHeightTexture generate_layer_height_texture(
    const Domain::LayerZRanges& color_layers,
    const Domain::LayerZRanges& stripe_layers,
    double min_layer_height,
    double max_layer_height,
    double layer_height,
    double object_height
);

/**
 * Compute a new height range to be inserted among existing ranges.
 *
 * Determines the Z boundaries of a new range based on the currently selected range.
 * If a range is selected, the new range is placed after it - either in a gap, by splitting
 * an adjacent range, or after the last range. If no range is selected, the new range is
 * placed after all existing ranges, or at the origin if no ranges exist.
 *
 * @param selected Currently selected range, or nullopt if none.
 * @param next_after_selected First range after the selected one, or nullopt if selected is last.
 * @param max_existing_z Highest max_z across all existing ranges (0 if empty).
 * @param object_max_z Maximum Z height of the object, new ranges are clamped to this value.
 * @param min_layer_height Minimum allowed layer height, used when splitting adjacent ranges.
 * @return The new height range, or nullopt if there is no space to insert one.
 */
std::optional<Domain::LayerHeightRange> compute_new_height_range(
    const std::optional<Domain::LayerHeightRange>& selected,
    const std::optional<Domain::LayerHeightRange>& next_after_selected,
    double max_existing_z,
    double object_max_z,
    double min_layer_height
);

class LayerHeightMaterialWrapper
{
public:
    LayerHeightMaterialWrapper()  = default;
    ~LayerHeightMaterialWrapper() = default;

    void init(Render::Device& device);

    void reset();

    /**
     * Get the material for applying to scene nodes.
     */
    const Render::Material& material() const;

    /**
     * Set layer data and regenerate texture.
     *
     * @param color_layers Layers for palette color mapping.
     * @param stripe_layers Layers for visualizing layer height boundaries via intensity modulation.
     * @param min_layer_height Minimum allowed layer height.
     * @param max_layer_height Maximum allowed layer height.
     * @param layer_height Default layer height.
     * @param object_height Total Z height of the object.
     * @param object_max_z Maximum Z of the object.
     */
    void set_layers(
        const Domain::LayerZRanges& color_layers,
        const Domain::LayerZRanges& stripe_layers,
        double min_layer_height,
        double max_layer_height,
        double layer_height,
        double object_height,
        float object_max_z
    );

    /**
     * Set the cursor Z position.
     */
    void set_cursor_z(float cursor_z);

    /**
     * Set the cursor band width.
     */
    void set_cursor_band_width(float band_width);

private:
    Render::Material m_material;
    Render::TexturePtr m_texture;
};

class HeightRangePlanesWrapper
{
public:
    HeightRangePlanesWrapper()  = default;
    ~HeightRangePlanesWrapper() = default;

    void init(Render::Device& device, Scene::Scene& scene, const Domain::ModelObject& model_object);
    void release(Scene::Scene& scene);
    void set_enabled(bool enabled);

    void set_planes_visible(bool visible);
    void set_positions(double min_z, double max_z, const Domain::ModelObject& model_object);
    void set_plane_default_color(HeightRangePlaneNodeTag::PlaneType plane_type);
    void set_plane_hover_color(HeightRangePlaneNodeTag::PlaneType plane_type);

private:
    using PlaneGeometryManager     = Render::GeometryManager<HeightRangePlaneNodeTag::PlaneType>;
    using PlaneTriangleMeshManager = Scene::TriangleMeshManager<HeightRangePlaneNodeTag::PlaneType>;

    PlaneGeometryManager m_geometry_manager{"height_range_planes_wrapper_geometry"};
    PlaneTriangleMeshManager m_triangle_mesh_manager{"height_range_planes_wrapper_mesh"};

    Scene::Node* m_main_node      = nullptr;
    Scene::Node* m_min_plane_node = nullptr;
    Scene::Node* m_max_plane_node = nullptr;

    void build_plane_node(
        Render::Device& device,
        Scene::NodeBuilder& builder,
        HeightRangePlaneNodeTag::PlaneType plane_type,
        const Domain::ModelObject& model_object
    );

    Scene::Node* plane_node(HeightRangePlaneNodeTag::PlaneType plane_type) const;

    void set_plane_color(Scene::Node* node, const Domain::ColorRGBA& color);
};

} // namespace Slic3r::App::Plater
