name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Before submitting a new issue, please search both open and closed issues to check if this has been reported before. If you find a similar issue, please add your information as a comment on the existing issue instead of creating a new one. We can reopen closed issues if needed.

  - type: textarea
    id: what-happened
    attributes:
      label: Bug Description
      description: |
        Please describe what happened and what you expected to happen instead. 
        Include screenshots whenever possible, even if the issue seems clear.
        For 3D rendering issues, please include the output from Help -> System Info.
      placeholder: |
        • What is the problem you encountered?
        • What did you expect to happen instead?
        • Drop any relevant screenshots here
    validations:
      required: true

  - type: textarea
    id: to_reproduce
    attributes:
      label: Project File & Reproduction Steps
      description: |
        Please upload your project file as a ZIP archive. Export it right before the issue occurs, even if the project is empty - this helps us see your configuration.
        
        To export: File -> Save project as... -> Create ZIP
      placeholder: |
        1. Drop your project ZIP file here
        2. List the steps to reproduce the issue:
           • Open PrusaSlicer
           • Click on...
           • etc.
    validations:
      required: true

  - type: checkboxes
    id: files-included
    attributes:
      label: Submission Checklist
      options:
        - label: I have attached the project file
          required: true
        - label: I have included relevant screenshots
          required: true

  - type: input
    id: version
    attributes:
      label: PrusaSlicer Version
      description: Check Help -> About PrusaSlicer for your exact version number
      placeholder: 2.4.1-alpha2-win64, 2.3.3-linux, 2.4.1-alpha0+61-win64-gcd2459455
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Please include your OS version
      placeholder: Windows 11, Ubuntu 22.04, macOS 13.1
    validations:
      required: true

  - type: input
    id: printer
    attributes:
      label: Printer Model
      description: Please specify your printer model (required even if the issue seems unrelated)
      placeholder: Voron 2.4 with Afterburner
    validations:
      required: true