contact_links:
  - name: PrusaSlicer Manual and Support
    url: https://help.prusa3d.com/en/article/customer-support_2287/
    about: If you are not sure that what you are reporting is really a bug, please, consult the manual first.
  - name: PrusaPrinters Forum
    url: https://forum.prusaprinters.org/forum/prusaslicer/
    about: Please get in touch on our PrusaPrinters Community Forum! (Not an official support channel.)
    
blank_issues_enabled: false
