#include <algorithm>

#include "Slic3r/Domain/FacetsAnnotation.hpp"
#include "Slic3r/Domain/TriangleSelector.hpp"
#include "Slic3r/Assert.hpp"

namespace Slic3r::Domain {

void FacetsAnnotation::assign(const FacetsAnnotation& rhs)
{
    if (this->timestamp_matches(rhs))
        return;

    this->triangle_splitting_data = rhs.triangle_splitting_data;
    this->copy_timestamp(rhs);
}

void FacetsAnnotation::assign(FacetsAnnotation&& rhs)
{
    if (this->timestamp_matches(rhs))
        return;

    this->triangle_splitting_data = std::move(rhs.triangle_splitting_data);
    this->copy_timestamp(rhs);
}

const TriangleSelector::TriangleSplittingData& FacetsAnnotation::get_data() const noexcept
{
    return this->triangle_splitting_data;
}

bool FacetsAnnotation::set_data(
    TriangleSelector::TriangleSplittingData&& new_triangle_splitting_data
)
{
    if (new_triangle_splitting_data != this->triangle_splitting_data) {
        triangle_splitting_data = std::move(new_triangle_splitting_data);
        this->touch();
        return true;
    }

    return false;
}

bool FacetsAnnotation::empty() const
{
    return this->triangle_splitting_data.triangles_to_split.empty();
}

void FacetsAnnotation::reset()
{
    this->triangle_splitting_data.triangles_to_split.clear();
    this->triangle_splitting_data.bitstream.clear();
    this->touch();
}

void FacetsAnnotation::reserve(int n_triangles)
{
    this->triangle_splitting_data.triangles_to_split.reserve(n_triangles);
}

// Following function takes data from a triangle and encodes it as string
// of hexadecimal numbers (one digit per triangle). Used for 3MF export,
// changing it may break backwards compatibility !!!!!
std::string FacetsAnnotation::get_triangle_as_string(int triangle_idx) const
{
    std::string out;

    auto triangle_it = std::lower_bound(this->triangle_splitting_data.triangles_to_split.begin(), this->triangle_splitting_data.triangles_to_split.end(), triangle_idx, [](const Domain::TriangleSelector::TriangleBitStreamMapping &l, const int r) { return l.triangle_idx < r; });
    if (triangle_it != this->triangle_splitting_data.triangles_to_split.end() && triangle_it->triangle_idx == triangle_idx) {
        int offset = triangle_it->bitstream_start_idx;
        int end    = ++triangle_it == this->triangle_splitting_data.triangles_to_split.end() ? int(this->triangle_splitting_data.bitstream.size()) : triangle_it->bitstream_start_idx;
        while (offset < end) {
            int next_code = 0;
            for (int i = 3; i >= 0; --i) {
                next_code = next_code << 1;
                next_code |= int(this->triangle_splitting_data.bitstream[offset + i]);
            }
            offset += 4;

            ASSERT(next_code >= 0 && next_code <= 15);
            char digit = next_code < 10 ? next_code + '0' : (next_code - 10) + 'A';
            out.insert(out.begin(), digit);
        }
    }

    return out;
}

// Recover triangle splitting & state from string of hexadecimal values previously
// generated by get_triangle_as_string. Used to load from 3MF.
void FacetsAnnotation::set_triangle_from_string(int triangle_id, const std::string &str)
{
    if (str.empty()) {
        // The triangle isn't painted, so it means that it will use the default extruder.
        this->triangle_splitting_data.used_states[static_cast<int>(TriangleSelector::TriangleStateType::NONE)] = true;
        return;
    }

    ASSERT(!str.empty());
    ASSERT(this->triangle_splitting_data.triangles_to_split.empty() || this->triangle_splitting_data.triangles_to_split.back().triangle_idx < triangle_id);
    this->triangle_splitting_data.triangles_to_split.emplace_back(triangle_id, int(this->triangle_splitting_data.bitstream.size()));

    const size_t bitstream_start_idx = this->triangle_splitting_data.bitstream.size();
    for (auto it = str.crbegin(); it != str.crend(); ++it) {
        const char ch = *it;
        int dec = 0;
        if (ch >= '0' && ch <= '9') {
            dec = int(ch - '0');
        } else if (ch >= 'A' && ch <= 'F') {
            dec = 10 + int(ch - 'A');
        } else {
            ASSERT(false);
        }

        // Convert to binary and append into code.
        for (int i = 0; i < 4; ++i) {
            this->triangle_splitting_data.bitstream.insert(this->triangle_splitting_data.bitstream.end(), bool(dec & (1 << i)));
        }
    }

    this->triangle_splitting_data.update_used_states(bitstream_start_idx);
}

void FacetsAnnotation::shrink_to_fit()
{
    this->triangle_splitting_data.triangles_to_split.shrink_to_fit();
    this->triangle_splitting_data.bitstream.shrink_to_fit();
}

} // namespace Slic3r::Domain
