#pragma once

#include <vector>

#include "Slic3r/Domain/ObjectID.hpp"
#include "Slic3r/Domain/Types.hpp"

namespace Slic3r::Biz::Slicing {

// One support spot generated by the support spots generation step of the slicing process.
struct GeneratedSupportPoint
{
    // Position in print object coordinates (unscaled). The z coordinate is aligned with the layers bottom_z coordinates.
    Domain::Vec3f position;
    // Expected support spot radius.
    float spot_radius{};
};

using GeneratedSupportPoints = std::vector<GeneratedSupportPoint>;

struct ObjectSupportPoints
{
    Domain::ObjectID model_object_id;
    // Transforms model object coordinates into print object coordinates.
    Domain::Transform3d object_transform;
    GeneratedSupportPoints support_points;
};

using GeneratedSupportPointsSnapshot = std::vector<ObjectSupportPoints>;

} // namespace Slic3r::Biz::Slicing
