
#pragma once

#include <vector>
#include <string>
#include <optional>
#include "Slic3r/Domain/Types.hpp"
#include "Slic3r/Domain/Constants.hpp"

namespace Slic3r::Domain {

/// <summary>
/// User modifiable property of text style
/// NOTE: OnEdit fix serializations: EmbossStylesSerializable, TextConfigurationSerialization
/// </summary>
struct FontProp
{
    // define extra space between letters, negative mean closer letter
    // When not set value is zero and is not stored
    std::optional<int> char_gap; // [in font point]

    // define extra space between lines, negative mean closer lines
    // When not set value is zero and is not stored
    std::optional<int> line_gap; // [in font point]

    // positive value mean wider character shape
    // negative value mean tiner character shape
    // When not set value is zero and is not stored
    std::optional<float> boldness; // [in mm]

    // positive value mean italic of character (CW)
    // negative value mean CCW skew (unItalic)
    // When not set value is zero and is not stored
    std::optional<float> skew; // [ration x:y]

    // Parameter for True Type Font collections
    // Select index of font in collection
    std::optional<unsigned int> collection_number;

    // Distiguish projection per glyph
    bool per_glyph;

    // NOTE: way of serialize to 3mf force that zero must be default value
    enum class HorizontalAlign
    {
        left = 0,
        center,
        right
    };
    enum class VerticalAlign
    {
        top = 0,
        center,
        bottom
    };
    struct Align
    {
        HorizontalAlign horizontal{ HorizontalAlign::center };
        VerticalAlign vertical{VerticalAlign::center};
        bool operator==(const Align& other) const;
    };
    // change pivot of text
    // When not set, center is used and is not stored
    Align align;

    //////
    // Duplicit data to wxFontDescriptor
    // used for store/load .3mf file
    //////

    // Height of text line (letters)
    // duplicit to wxFont::PointSize
    float size_in_mm; // [in mm]

    // Additional data about font to be able to find substitution,
    // when same font is not installed
    std::optional<std::string> family;
    std::optional<std::string> face_name;
    std::optional<std::string> style;
    std::optional<std::string> weight;

    /// <summary>
    /// Only constructor with restricted values
    /// </summary>
    /// <param name="line_height">Y size of text [in mm]</param>
    /// <param name="depth">Z size of text [in mm]</param>
    FontProp(float line_height = 10.f);

    bool operator==(const FontProp& other) const;
};

/// <summary>
/// Describe how to access font data
/// </summary>
struct FontDescriptor
{
    // Human readable name of style it is shown in GUI
    // Hint for user when font is not installed on current OS
    std::string name;

    // Define how to open font
    // Meaning depend on type
    std::string path;

    // when name is empty than Font item was loaded from .3mf file
    // and potentionaly it is not reproducable
    // define data stored in path
    // when wx change way of storing add new descriptor Type
    enum class Type
    {
        undefined = 0,

        // wx font descriptors are platform dependent
        // path is font descriptor generated by wxWidgets
        wx_win_font_descr, // on Windows
        wx_lin_font_descr, // on Linux
        wx_mac_font_descr, // on Max OS

        // TrueTypeFont file loacation on computer
        // for privacy: only filename is stored into .3mf
        file_path
    };
    Type type;

    bool operator==(const FontDescriptor& other) const;
};

using FontList = std::vector<FontDescriptor>;

/// <summary>
/// Preset of embossed text
/// (Path + Type) must define how to open font for using on different OS
/// NOTE: OnEdit fix serializations: EmbossStylesSerializable, TextConfigurationSerialization
/// </summary>
struct EmbossStyle
{
    // Define where to find font file data
    // + hint user which font is needed to install
    FontDescriptor descriptor;

    // User modification of font style
    FontProp prop;

    bool operator==(const EmbossStyle& other) const;
};

// Emboss style name inside vector is unique
// It is not map beacuse items has own order (view inside of slect)
// It is stored into AppConfig by EmbossStylesSerializable
using EmbossStyles = std::vector<EmbossStyle>;

/// <summary>
/// Define how to create 'Text volume'
/// It is stored into .3mf by TextConfigurationSerialization
/// It is part of ModelVolume optional data
/// </summary>
struct TextConfiguration
{
    // Preset of embossed text
    EmbossStyle style;

    // Embossed text value
    std::string text = "None";
};

} // namespace Slic3r::Domain
