cmake_minimum_required(VERSION 3.13)
if(NOT DEFINED ORCA_PROFILES_DESTINATION OR ORCA_PROFILES_DESTINATION STREQUAL "")
    message(FATAL_ERROR "ORCA_PROFILES_DESTINATION is required")
endif()
# Deliberately do not repair, update, or even inspect an existing profile tree.
if(EXISTS "${ORCA_PROFILES_DESTINATION}" OR IS_SYMLINK "${ORCA_PROFILES_DESTINATION}")
    return()
endif()
get_filename_component(_orca_parent "${ORCA_PROFILES_DESTINATION}" DIRECTORY)
file(MAKE_DIRECTORY "${_orca_parent}")
file(LOCK "${_orca_parent}/.orca-profiles-download.lock" GUARD PROCESS TIMEOUT 600)
if(EXISTS "${ORCA_PROFILES_DESTINATION}" OR IS_SYMLINK "${ORCA_PROFILES_DESTINATION}")
    return()
endif()
find_package(Git 2.25 REQUIRED)
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef _orca_nonce)
set(_orca_stage "${_orca_parent}/.orca-profiles-download-${_orca_nonce}")
message(STATUS "Fetching all OrcaSlicer profiles from main")
function(_orca_git)
    execute_process(COMMAND "${GIT_EXECUTABLE}" ${ARGN}
        RESULT_VARIABLE _orca_result TIMEOUT 600)
    if(NOT _orca_result STREQUAL "0")
        file(REMOVE_RECURSE "${_orca_stage}")
        message(FATAL_ERROR "Orca profile download failed (${_orca_result}); rerun configure/build to retry")
    endif()
endfunction()
_orca_git(clone --depth 1 --filter=blob:none --sparse --single-branch --branch main
    https://github.com/OrcaSlicer/OrcaSlicer.git "${_orca_stage}")
_orca_git(-C "${_orca_stage}" sparse-checkout set resources/profiles)
if(NOT EXISTS "${_orca_stage}/resources/profiles/OrcaFilamentLibrary.json")
    file(REMOVE_RECURSE "${_orca_stage}")
    message(FATAL_ERROR "Downloaded Orca profile tree is missing OrcaFilamentLibrary.json")
endif()
# Same-filesystem rename publishes only the completed tree.
if(NOT EXISTS "${ORCA_PROFILES_DESTINATION}" AND NOT IS_SYMLINK "${ORCA_PROFILES_DESTINATION}")
    file(RENAME "${_orca_stage}/resources/profiles" "${ORCA_PROFILES_DESTINATION}")
endif()
file(REMOVE_RECURSE "${_orca_stage}")
