#include "Slic3r/App/Platform/KeyCode.hpp"

#include "Slic3r/Assert.hpp"

#include <map>
#include "fmt/format.h"

// Define our own marking functions, the regular ones are not accessible in Platform.
static const std::string L(const std::string& s)
{
    return s;
}

namespace Slic3r::App::Platform {

struct Key
{
    std::string display_name = std::string(); // Human-readable (UI, tooltips, menus)
    std::string accel_name   = std::string(); // wxAccelerator / platform-specific name
};

static const std::map<KeyCode, Key> key_code_mapping = {
    {KeyCode::None, {}},
    {KeyCode::Return, {L("Return"), "Return"}},
    {KeyCode::Escape, {L("Escape"), "Esc"}},
    {KeyCode::Backspace, {L("Backspace"), "Backspace"}},
    {KeyCode::Tab, {L("Tab"), "Tab"}},
    {KeyCode::Space, {L("Space"), "Space"}},
    {KeyCode::Exclaim, {"!"}},
    {KeyCode::QuoteDbl, {"\""}},
    {KeyCode::Hash, {"#"}},
    {KeyCode::Percent, {"%"}},
    {KeyCode::Dollar, {"$"}},
    {KeyCode::Ampersand, {"&"}},
    {KeyCode::Quote, {"\'", "'"}},
    {KeyCode::LeftParen, {"("}},
    {KeyCode::RightParen, {")"}},
    {KeyCode::Asterisk, {"*", "Multiply"}},
    {KeyCode::Plus, {"+", "Add"}},
    {KeyCode::Comma, {",", ","}},
    {KeyCode::Minus, {"-", "Subtract"}},
    {KeyCode::Period, {".", "Decimal"}},
    {KeyCode::Slash, {"/", "Divide"}},
    {KeyCode::Num0, {"0", "0"}},
    {KeyCode::Num1, {"1", "1"}},
    {KeyCode::Num2, {"2", "2"}},
    {KeyCode::Num3, {"3", "3"}},
    {KeyCode::Num4, {"4", "4"}},
    {KeyCode::Num5, {"5", "5"}},
    {KeyCode::Num6, {"6", "6"}},
    {KeyCode::Num7, {"7", "7"}},
    {KeyCode::Num8, {"8", "8"}},
    {KeyCode::Num9, {"9", "9"}},
    {KeyCode::Colon, {":"}},
    {KeyCode::Semicolon, {";"}},
    {KeyCode::Less, {"<"}},
    {KeyCode::Equals, {"=", "="}},
    {KeyCode::Greater, {">"}},
    {KeyCode::Question, {"?"}},
    {KeyCode::At, {"@"}},
    {KeyCode::LeftBracket, {"["}},
    {KeyCode::Backslash, {"\\"}},
    {KeyCode::RightBracket, {"]"}},
    {KeyCode::Caret, {"^"}},
    {KeyCode::Underscore, {"_"}},
    {KeyCode::Backquote, {"`"}},
    {KeyCode::A, {"A", "A"}},
    {KeyCode::B, {"B", "B"}},
    {KeyCode::C, {"C", "C"}},
    {KeyCode::D, {"D", "D"}},
    {KeyCode::E, {"E", "E"}},
    {KeyCode::F, {"F", "F"}},
    {KeyCode::G, {"G", "G"}},
    {KeyCode::H, {"H", "H"}},
    {KeyCode::I, {"I", "I"}},
    {KeyCode::J, {"J", "J"}},
    {KeyCode::K, {"K", "K"}},
    {KeyCode::L, {"L", "L"}},
    {KeyCode::M, {"M", "M"}},
    {KeyCode::N, {"N", "N"}},
    {KeyCode::O, {"O", "O"}},
    {KeyCode::P, {"P", "P"}},
    {KeyCode::Q, {"Q", "Q"}},
    {KeyCode::R, {"R", "R"}},
    {KeyCode::S, {"S", "S"}},
    {KeyCode::T, {"T", "T"}},
    {KeyCode::U, {"U", "U"}},
    {KeyCode::V, {"V", "V"}},
    {KeyCode::W, {"W", "W"}},
    {KeyCode::X, {"X", "X"}},
    {KeyCode::Y, {"Y", "Y"}},
    {KeyCode::Z, {"Z", "Z"}},
    {KeyCode::CapsLock, {L("CapsLock"), "Capital"}},
    {KeyCode::F1, {"F1", "F1"}},
    {KeyCode::F2, {"F2", "F2"}},
    {KeyCode::F3, {"F3", "F3"}},
    {KeyCode::F4, {"F4", "F4"}},
    {KeyCode::F5, {"F5", "F5"}},
    {KeyCode::F6, {"F6", "F6"}},
    {KeyCode::F7, {"F7", "F7"}},
    {KeyCode::F8, {"F8", "F8"}},
    {KeyCode::F9, {"F9", "F9"}},
    {KeyCode::F10, {"F10", "F10"}},
    {KeyCode::F11, {"F11", "F11"}},
    {KeyCode::F12, {"F12", "F12"}},
    {KeyCode::PrintScreen, {"PrintScreen", "Snapshot"}},
    {KeyCode::ScrollLock, {L("Scroll Lock"), "Scroll_lock"}},
    {KeyCode::Pause, {L("Pause"), "Pause"}},
    {KeyCode::Insert, {L("Ins"), "Insert"}},
    {KeyCode::Home, {L("Home"), "Home"}},
    {KeyCode::PageUp, {L("Page Up"), "PageUp"}},
    {KeyCode::Delete, {L("Del"), "Del"}},
    {KeyCode::End, {L("End"), "End"}},
    {KeyCode::PageDown, {L("Page Down"), "PageDown"}},
    {KeyCode::Right, {L("Arrow Right"), "Right"}},
    {KeyCode::Left, {L("Arrow Left"), "Left"}},
    {KeyCode::Down, {L("Arrow Down"), "Down"}},
    {KeyCode::Up, {L("Arrow Up"), "Up"}},
    {KeyCode::NumLockClear, {L("NumLockClear"), "Clear"}},
    {KeyCode::KpDivide, {("/"), "KP_Divide"}},
    {KeyCode::KpMultiply, {("*"), "KP_Multiply"}},
    {KeyCode::KpMinus, {("-"), "KP_Subtract"}},
    {KeyCode::KpPlus, {("+"), "KP_Add"}},
    {KeyCode::KpEnter, {L("Enter"), "KP_Enter"}},
    {KeyCode::Kp0, {"0", "KP_0"}},
    {KeyCode::Kp1, {"1", "KP_1"}},
    {KeyCode::Kp2, {"2", "KP_2"}},
    {KeyCode::Kp3, {"3", "KP_3"}},
    {KeyCode::Kp4, {"4", "KP_4"}},
    {KeyCode::Kp5, {"5", "KP_5"}},
    {KeyCode::Kp6, {"6", "KP_6"}},
    {KeyCode::Kp7, {"7", "KP_7"}},
    {KeyCode::Kp8, {"8", "KP_8"}},
    {KeyCode::Kp9, {"9", "KP_9"}},
    {KeyCode::KpPeriod, {".", "KP_Decimal"}},
    {KeyCode::Application, {}},
    {KeyCode::Power, {}},
    {KeyCode::KpEquals, {"=", "KP_Equal"}},
    {KeyCode::F13, {"F13", "F13"}},
    {KeyCode::F14, {"F14", "F14"}},
    {KeyCode::F15, {"F15", "F15"}},
    {KeyCode::F16, {"F16", "F16"}},
    {KeyCode::F17, {"F17", "F17"}},
    {KeyCode::F18, {"F18", "F18"}},
    {KeyCode::F19, {"F19", "F19"}},
    {KeyCode::F20, {"F20", "F20"}},
    {KeyCode::F21, {"F21", "F21"}},
    {KeyCode::F22, {"F22", "F22"}},
    {KeyCode::F23, {"F23", "F23"}},
    {KeyCode::F24, {"F24", "F24"}},
    {KeyCode::Execute, {L("Execute"), "Execute"}},
    {KeyCode::Help, {L("Help"), "Help"}},
    {KeyCode::Menu, {L("Menu"), "Menu"}},
    {KeyCode::Select, {L("Select"), "Select"}},
    {KeyCode::Stop, {}},
    {KeyCode::Again, {}},
    {KeyCode::Undo, {}},
    {KeyCode::Cut, {}},
    {KeyCode::Copy, {}},
    {KeyCode::Paste, {}},
    {KeyCode::Find, {}},
    {KeyCode::Mute, {}},
    {KeyCode::VolumeUp, {}},
    {KeyCode::VolumeDown, {}},
    {KeyCode::KpComma, {",", "KP_Separator"}},
    {KeyCode::KpEqualsAs400, {}},
    {KeyCode::AltErase, {}},
    {KeyCode::SysReq, {}},
    {KeyCode::Cancel, {L("Cancel"), "Cancel"}},
    {KeyCode::Clear, {L("Clear"), "Clear"}},
    {KeyCode::Prior, {}},
    {KeyCode::Return2, {}},
    {KeyCode::Separator, {"", "Separator"}},
    {KeyCode::Out, {}},
    {KeyCode::Oper, {}},
    {KeyCode::ClearAgain, {}},
    {KeyCode::CrSel, {}},
    {KeyCode::ExSel, {}},
    {KeyCode::Kp00, {}},
    {KeyCode::Kp000, {}},
    {KeyCode::ThousandsSeparator, {}},
    {KeyCode::DecimalSeparator, {}},
    {KeyCode::CurrencyUnit, {}},
    {KeyCode::CurrencySubunit, {}},
    {KeyCode::KpLeftParen, {}},
    {KeyCode::KpRightParen, {}},
    {KeyCode::KpLeftBrace, {}},
    {KeyCode::KpRightBrace, {}},
    {KeyCode::KpTab, {L("Tab"), "KP_Tab"}},
    {KeyCode::KpBackspace, {}},
    {KeyCode::KpA, {}},
    {KeyCode::KpB, {}},
    {KeyCode::KpC, {}},
    {KeyCode::KpD, {}},
    {KeyCode::KpE, {}},
    {KeyCode::KpF, {}},
    {KeyCode::KpXor, {}},
    {KeyCode::KpPower, {}},
    {KeyCode::KpPercent, {}},
    {KeyCode::KpLess, {}},
    {KeyCode::KpGreater, {}},
    {KeyCode::KpAmpersand, {}},
    {KeyCode::KpDblAmpersand, {}},
    {KeyCode::KpVerticalBar, {}},
    {KeyCode::KpDblVerticalBar, {}},
    {KeyCode::KpColon, {}},
    {KeyCode::KpHash, {}},
    {KeyCode::KpSpace, {L("Space"), "KP_Space"}},
    {KeyCode::KpAt, {}},
    {KeyCode::KpExclam, {}},
    {KeyCode::KpMemStore, {}},
    {KeyCode::KpMemRecall, {}},
    {KeyCode::KpMemClear, {}},
    {KeyCode::KpMemAdd, {}},
    {KeyCode::KpMemSubtract, {}},
    {KeyCode::KpMemMultiply, {}},
    {KeyCode::KpMemDivide, {}},
    {KeyCode::KpPlusMinus, {}},
    {KeyCode::KpClear, {}},
    {KeyCode::KpClearEntry, {}},
    {KeyCode::KpBinary, {}},
    {KeyCode::KpOctal, {}},
    {KeyCode::KpDecimal, {}},
    {KeyCode::KpHexadecimal, {}},
    {KeyCode::LCtrl, {}},
    {KeyCode::LShift, {}},
    {KeyCode::LAlt, {}},
    {KeyCode::LMeta, {}},
    {KeyCode::RCtrl, {}},
    {KeyCode::RShift, {}},
    {KeyCode::RAlt, {}},
    {KeyCode::RMeta, {}},
    {KeyCode::Mode, {}},
    {KeyCode::AudioNext, {}},
    {KeyCode::AudioPrev, {}},
    {KeyCode::AudioStop, {}},
    {KeyCode::AudioPlay, {}},
    {KeyCode::AudioMute, {}},
    {KeyCode::MediaSelect, {}},
    {KeyCode::Www, {}},
    {KeyCode::Mail, {}},
    {KeyCode::Calculator, {}},
    {KeyCode::Computer, {}},
    {KeyCode::AcSearch, {}},
    {KeyCode::AcHome, {}},
    {KeyCode::AcBack, {}},
    {KeyCode::AcForward, {}},
    {KeyCode::AcStop, {}},
    {KeyCode::AcRefresh, {}},
    {KeyCode::AcBookmarks, {}},
    {KeyCode::BrightnessDown, {}},
    {KeyCode::BrightnessUp, {}},
    {KeyCode::DisplaySwitch, {}},
    {KeyCode::KbdIllumToggle, {}},
    {KeyCode::KbdIllumDown, {}},
    {KeyCode::KbdIllumUp, {}},
    {KeyCode::Eject, {}},
    {KeyCode::Sleep, {}},
    {KeyCode::App1, {}},
    {KeyCode::App2, {}},
    {KeyCode::AudioRewind, {}},
    {KeyCode::AudioFastForward, {}},
    {KeyCode::SoftLeft, {}},
    {KeyCode::SoftRight, {}},
    {KeyCode::Call, {}},
    {KeyCode::EndCall, {}},
};

std::string to_string(KeyCode key_code)
{
    ASSERT(
        key_code_mapping.contains(key_code),
        fmt::format("KeyCode({}) doesn't exist in map", static_cast<int>(key_code))
    );

    Key key = key_code_mapping.at(key_code);
    ASSERT(
        !key.display_name.empty(),
        fmt::format("KeyCode({}) with no mapped string assigned", static_cast<int>(key_code))
    );

    return key.display_name;
}

std::string to_accel_table_string(KeyCode key_code)
{
    ASSERT(
        key_code_mapping.contains(key_code),
        fmt::format("KeyCode({}) doesn't exist in map", static_cast<int>(key_code))
    );

    Key key = key_code_mapping.at(key_code);
    ASSERT(
        !key.accel_name.empty(),
        fmt::format("KeyCode({}, \"{}\") with no accel string assigned", static_cast<int>(key_code), key.display_name)
    );

    return key.accel_name;
}

} // namespace Slic3r::App::Platform
