#pragma once

namespace Slic3r::App::Render {

enum class ImguiFontType
{
    Regular,
    Bold,
    Italic
};

enum class Icon : wchar_t
{
    None = 0x0,
    PrintIconMarker,
    FilamentIconMarker,
    MaterialIconMarker,
    WarningMarker,
    WarningMarkerWhite,
    ErrorMarker,
    RevertButton,

    // Do not forget use following letters only in wstring
    ClippyMarker,
    NotificationCloseGray,

    LegendTravel,
    LegendWipe,
    LegendRetract,
    LegendDeretract,
    LegendSeams,
    LegendToolChanges,
    LegendColorChanges,
    LegendPausePrints,
    LegendCustomGCodes,
    LegendCOG,
    LegendShells,
    LegendToolMarker,
    PrusaSlicerIcon,
    Printables,
    Connect,
    Cloud,
    Lock,
    Unlock,
    LightLockClosed,
    LightLockOpened,
    DSRevert,
    DSSettings,

    // icon for multiple beds
    PrintIdle,

    // icon for object list
    VariableLayerHeight,
    HeightRange,
    Details,
    SceneMap,
    // icon for help
    MouseLeft,
    MouseRight,
    MouseWheel,
    MouseDrag,
    KeyBackspace,
    Calculator,
    CopyForGizmo,

    // icons for toolbar
    ToolbarObjects,
    ToolbarHistory,
    ToolbarGCode,
    ToolbarGraph,
    ToolbarCut,

    // sidebar icons
    SavePrint,
    SavePrintToFlash,
    SavePrintToLocal,
    SavePrintAddBookmark,

    SettingsSet,
    TopBarUndo,
    TopBarRedo,
    TobBarLoad,
    TobBarSave,
    TobBarShowUI,
    TobBarPlus,
    TopBarCross,

    // Gizmo Paint-on-Supports
    Triangle,
    Circle,
    Square,
    Hexagon,
    Sphere,
    WandMagicSparkles,
    PaintBrush,
    Prism,
    Frustum,
    DividingLine,
    Dove,

    // Gizmo Multimaterial painting
    FillDrip,
    ColorReplace,
    LineHeight,
    Switch,

    // Gizmo Emboss
    NewBtnIcon,
    DeleteBtnIcon,
    AlignHLeftBtn,
    AlignHCenterBtn,
    AlignHRightBtn,
    AlignVTopBtn,
    AlignVCenterBtn,
    AlignVBottomBtn,

    // Gizmo Svg
    Reload,
    ReflectionX,
    ReflectionY,

    // Gizmo Arrange
    ArrangeTopLeft,
    ArrangeTopRight,
    ArrangeBottomLeft,
    ArrangeBottomRight,
    ArrangeCenter,
    MultipleSquares,
    SingleSquare,

    // Gizmo Layer Height
    ArrowUpToLine,
    ArrowUpFromLine,
    LayersIcon,
    MinusModifier,
    PlusHeightRange,
    PlusModifier,

    // Physical printer
    ExportToSD,
    ConnectUpload,
    ExportToLocal,

    Layers,
    WallsPerimeters,
    Infill,
    BedAdhesion,
    SkirtBrim,
    Support,
    Time,
    Motions,
    ExtrusionRetraction,
    MultiMaterial,
    Precision,
    CustomGCode,
    Temperature,
    ExtrusionCalibration,
    Vector,
    Bed,
    MachineLimits,
    MultipleExtruders,
    SingleExtruder,
    Funnel,
    Cog,
    Star,
    StarSolid,
    Cogs,
    Output,
    Notes,
    CaretLeft,
    CaretRight,
    CaretUp,
    CaretDown,
    Search,
    Fan,
    AddObject,
    AddVolume,
    Minus,
    ChevronRight,
    ChevronLeft,
    Compare,
    Hollowing,
    Pad,
    Preview,
    Move,
    Scale,
    PlaceOnFace,
    Ellipsis,
    Cube,
    CubeAdd,
    Layout,
    LayersInspect,
    PaintSupports,
    PaintSeams,
    PaintFuzzySkin,
    PaintMultiMaterial,
    Ruler,
    Text,
    Svg,
    Scissors,
    Cut,
    RectangleAdd,
    Rotate,
    Simplify,
    ExclamationTriangle,
    Plus,
    Chain,
    Unchain,
    SliderFloatEditBtnIcon,
    SliderFloatEditBtnPressedIcon,
    PlugMarker,
    DowelMarker,
    SnapMarker,
    UndoGizmo,
    CloseGizmo,
    OpenFolder,
    Shapes,
    RecentProjects,
    Filter,
    ArrowRight,
    PhysicalPrinterIcon,
    CheckMark,
    Robot,

    // FontIconS
    // DO NOT TOUCH, DO NOT CHANGE ORDER
    // This has to be in sync with the icon font file
    PrinterIconMarker    = 0xE000,
    PrinterSlaIconMarker = 0xE001,
    EyeOpen              = 0xE002,
    EyeClosed            = 0xE003,
    SolidPartVolume      = 0xE004,
    NegativeVolume       = 0xE005,
    ModifierVolume       = 0xE006,
    SupportBlocker       = 0xE007,
    SupportModifier      = 0xE008,
    TextSolidPartVolume  = 0xE009,
    TextNegativeVolume   = 0xE00A,
    TextModifierVolume   = 0xE00B,
    SvgSolidPartVolume   = 0xE00C,
    SvgNegativeVolume    = 0xE00D,
    SvgModifierVolume    = 0xE00E,
    ObjectIcon           = 0xE00F,
    HRModifier           = 0xE010,
    CustomSupports       = 0xE011,
    CustomSeam           = 0xE012,
    CutConnectors        = 0xE013,
    MmSegmentation       = 0xE014,
    Sinking              = 0xE015,
    FuzzySkin            = 0xE016,
    OpenArrow            = 0xE017,
    CloseArrow           = 0xE018,
    ConfigContainer      = 0xE019,
    InstancesIcon        = 0xE01A,
    AddBedIcon           = 0xE01B,
    DelBedIcon           = 0xE01C,
    OverridesMarker      = 0xE01D,
    AllBeds              = 0xE01E,
    Palette              = 0xE01F,
    ErrorTick            = 0xE020,
    ErrorTickHovered     = 0xE021,
    PausePrint           = 0xE022,
    PausePrintHovered    = 0xE023,
    EditGCode            = 0xE024,
    EditGCodeHovered     = 0xE025,
    RemoveTick           = 0xE026,
    RemoveTickHovered    = 0xE027,
};

} // namespace Slic3r::App::Render
